#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fontdelivery"
name = "font.delivery"
description.en = ""
description.fr = ""

version = "0.1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://font.delivery/"
demo = "https://font.delivery/"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/sfhorg/font.delivery"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "fontdl"
    in_subdir = false
    extract = false
    url = "https://github.com/sfhorg/font.delivery/releases/download/fontdl-v0.1.0/fontdl-v0.1.0-linux-amd64"
    sha256 = "40b5304ad0ccfb50c78e178ce4677db36585d53c0e55fec831ece3d888a99092"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
